import time
import keyboard  # For the emergency killswitch
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecFrameStack

# Import your custom gym environment
from environment.game_env import GameEnvironment

def main():
    print("🎮 Initializing GameBot-AI Inference Mode...")

    # 1. RECREATE THE ENVIRONMENT ARCHITECTURE
    # We use DummyVecEnv instead of SubprocVecEnv because we only want 1 live instance
    env = DummyVecEnv([lambda: GameEnvironment()])
    
    # 2. APPLY FRAME STACKING
    # CRITICAL: This MUST match the exact n_stack number you used in train.py!
    # If the model was trained to see 4 frames, it will crash if you only give it 1.
    env = VecFrameStack(env, n_stack=4)

    # 3. LOAD THE BEST MODEL
    # We load from the best_model folder generated by the EvalCallback during training
    model_path = "./models/best_model/best_model.zip"
    try:
        model = PPO.load(model_path, env=env)
        print(f"✅ Successfully loaded model: {model_path}")
    except FileNotFoundError:
        print(f"❌ Error: Could not find model at {model_path}. Did you train it yet?")
        return

    # 4. TAB-IN TIMER & SAFETY WARNING
    print("\n⚠️ WARNING: AI will take over inputs in 5 seconds.")
    print("⚠️ PRESS AND HOLD 'Q' AT ANY TIME TO KILL THE AI AND REGAIN CONTROL.")
    for i in range(5, 0, -1):
        print(f"Starting in {i}...")
        time.sleep(1)

    # 5. THE INFERENCE LOOP
    obs = env.reset()
    print("🤖 AI is now playing!")
    
    try:
        while True:
            # --- THE EMERGENCY KILLSWITCH ---
            if keyboard.is_pressed('q'):
                print("\n🛑 Killswitch activated! Shutting down AI.")
                break

            # --- THE 'THINKING' STEP ---
            # deterministic=True forces the AI to pick the action with the highest probability,
            # turning off the random exploration it used during training.
            action, _states = model.predict(obs, deterministic=True)

            # --- THE 'DOING' STEP ---
            # Execute the input, update the screen, read the memory
            obs, rewards, dones, info = env.step(action)

    except Exception as e:
        print(f"\n❌ An error occurred during gameplay: {e}")
    finally:
        # 6. CLEANUP
        # Ensures virtual gamepads are released and memory hooks are closed cleanly
        env.close()
        print("🔌 AI Disconnected. You have control again.")

if __name__ == "__main__":
    main()
